/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendamentoResponseDTO { 
    idAgendamento?: number;
    idAnimal?: number;
    nomeAnimal?: string;
    idVet?: number;
    nomeVeterinario?: string;
    data?: string;
    hora?: string;
    status?: AgendamentoResponseDTO.StatusEnum;
    anotacoes?: string;
}
export namespace AgendamentoResponseDTO {
    export const StatusEnum = {
        Agendado: 'AGENDADO',
        Finalizado: 'FINALIZADO',
        Cancelado: 'CANCELADO'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


