/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendaConfigResponseDTO { 
    idConfig?: number;
    idVet?: number;
    /**
     * 1=Segunda ... 7=Domingo
     */
    diaSemana?: number;
    horaInicio?: string;
    horaFim?: string;
}

