/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendaConfigRequestDTO { 
    /**
     * Id do Veterinario ao qual este turno pertence
     */
    idVet: number;
    /**
     * 1=Segunda, 2=Terça, 3=Quarta, 4=Quinta, 5=Sexta, 6=Sábado, 7=Domingo
     */
    diaSemana: number;
    horaInicio: string;
    horaFim: string;
}

