/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendamentoStatusUpdateDTO { 
    /**
     * FINALIZADO ou CANCELADO
     */
    status: AgendamentoStatusUpdateDTO.StatusEnum;
    /**
     * Obrigatório ao finalizar ou cancelar.
     */
    anotacoes?: string;
}
export namespace AgendamentoStatusUpdateDTO {
    export const StatusEnum = {
        Agendado: 'AGENDADO',
        Finalizado: 'FINALIZADO',
        Cancelado: 'CANCELADO'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


