/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AgendamentoRequestDTO { 
    idAnimal: number;
    idVet: number;
    /**
     * Data da consulta (hoje ou futura)
     */
    data: string;
    /**
     * Horário da consulta, formato exclusivo HH:mm. Deve estar dentro do turno do veterinário.
     */
    hora: string;
    anotacoes?: string;
}

