/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnimalDTO { 
    readonly idAnimal?: number;
    /**
     * Id do Tutor responsável pelo animal
     */
    idTutor: number;
    nome: string;
    especie: string;
    raca?: string;
    /**
     * Idade em anos
     */
    idade?: number;
    /**
     * Peso em quilogramas
     */
    peso?: number;
    /**
     * Ex: MACHO ou FEMEA
     */
    sexo?: string;
}

