/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClinicaDTO { 
    readonly idClinica?: number;
    /**
     * Apenas números, 14 dígitos. Usado no login institucional.
     */
    cnpj: string;
    razaoSocial: string;
    nomeFantasia?: string;
}

