/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginRequestDTO { 
    /**
     * Apenas números, 11 dígitos
     */
    cpf: string;
    senha: string;
}

