/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsuarioResponseDTO } from './usuarioResponseDTO';


export interface LoginResponseDTO { 
    /**
     * Token JWT. Envie como \'Authorization: Bearer {token}\'
     */
    token?: string;
    usuario?: UsuarioResponseDTO;
}

