/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TutorDTO { 
    readonly idTutor?: number;
    /**
     * Id da clínica à qual este tutor pertence
     */
    idClinica: number;
    nome: string;
    /**
     * Apenas números, 11 dígitos
     */
    cpf: string;
    telefone?: string;
    endereco?: string;
}

