/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioResponseDTO { 
    idUsuario?: number;
    /**
     * Nulo quando perfil = ADMIN
     */
    idClinica?: number;
    cpf?: string;
    nome?: string;
    perfil?: UsuarioResponseDTO.PerfilEnum;
    crmv?: string;
    telefone?: string;
    /**
     * Turno Segunda-Sexta. Nulo quando perfil != VETERINARIO
     */
    horarioInicio?: string;
    /**
     * Turno Segunda-Sexta. Nulo quando perfil != VETERINARIO
     */
    horarioFim?: string;
    atendeSabado?: boolean;
    atendeDomingo?: boolean;
}
export namespace UsuarioResponseDTO {
    export const PerfilEnum = {
        Admin: 'ADMIN',
        Gestor: 'GESTOR',
        Veterinario: 'VETERINARIO',
        Recepcionista: 'RECEPCIONISTA'
    } as const;
    export type PerfilEnum = typeof PerfilEnum[keyof typeof PerfilEnum];
}


