/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioUpdateDTO { 
    idClinica?: number;
    cpf: string;
    /**
     * Opcional. Se omitida/em branco, a senha atual é mantida.
     */
    senha?: string;
    nome: string;
    perfil: UsuarioUpdateDTO.PerfilEnum;
    /**
     * Obrigatório e único quando perfil = VETERINARIO.
     */
    crmv?: string;
    telefone?: string;
    /**
     * Horário de início do turno Segunda-Sexta (sempre ativo). Formato exclusivo HH:mm.
     */
    horarioInicio?: string;
    /**
     * Horário de fim do turno Segunda-Sexta (sempre ativo). Formato exclusivo HH:mm.
     */
    horarioFim?: string;
    atendeSabado?: boolean;
    atendeDomingo?: boolean;
}
export namespace UsuarioUpdateDTO {
    export const PerfilEnum = {
        Admin: 'ADMIN',
        Gestor: 'GESTOR',
        Veterinario: 'VETERINARIO',
        Recepcionista: 'RECEPCIONISTA'
    } as const;
    export type PerfilEnum = typeof PerfilEnum[keyof typeof PerfilEnum];
}


