/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioRequestDTO { 
    idClinica?: number;
    cpf: string;
    senha: string;
    nome: string;
    /**
     * ADMIN, GESTOR, VETERINARIO ou RECEPCIONISTA
     */
    perfil: UsuarioRequestDTO.PerfilEnum;
    /**
     * Obrigatório e único quando perfil = VETERINARIO.
     */
    crmv?: string;
    /**
     * Opcional. Usado apenas quando perfil = VETERINARIO.
     */
    telefone?: string;
    /**
     * Horário de início do turno Segunda-Sexta (sempre ativo). Obrigatório quando perfil = VETERINARIO. Formato exclusivo HH:mm.
     */
    horarioInicio?: string;
    /**
     * Horário de fim do turno Segunda-Sexta (sempre ativo). Obrigatório quando perfil = VETERINARIO. Formato exclusivo HH:mm.
     */
    horarioFim?: string;
    /**
     * Se true, também atende aos Sábados, no mesmo horarioInicio–horarioFim.
     */
    atendeSabado?: boolean;
    /**
     * Se true, também atende aos Domingos, no mesmo horarioInicio–horarioFim.
     */
    atendeDomingo?: boolean;
}
export namespace UsuarioRequestDTO {
    export const PerfilEnum = {
        Admin: 'ADMIN',
        Gestor: 'GESTOR',
        Veterinario: 'VETERINARIO',
        Recepcionista: 'RECEPCIONISTA'
    } as const;
    export type PerfilEnum = typeof PerfilEnum[keyof typeof PerfilEnum];
}


