/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VeterinarioResponseDTO { 
    idVet?: number;
    idUsuario?: number;
    idClinica?: number;
    cpf?: string;
    nomeUsuario?: string;
    crmv?: string;
    telefone?: string;
}

