/**
 * SaudePetClinic API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VeterinarioRequestDTO { 
    /**
     * Id da clínica à qual o veterinário pertence
     */
    idClinica: number;
    /**
     * CPF do veterinário — apenas números, 11 dígitos. Usado no login.
     */
    cpf: string;
    /**
     * Senha de acesso ao sistema (mínimo 6 caracteres)
     */
    senha: string;
    nome: string;
    crmv: string;
    telefone?: string;
}

